#!/usr/bin/env bash

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
filter=""
dry="0"

# Parse args
while [[ $# > 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    else
        filter="$1"
        # Note: no support for array of filters
	    # A good rule of thumb is to reach for interpreted languages like JS or Python when
	    # Needing to deal with arrays
    fi
    
    shift
done

log() {
    if [[ $dry == "1" ]]; then
	    echo "[DRY RUN]: $@"
    else
	    echo "$@"
    fi
}

execute() {
    log "Execute: $@"
    
    if [[ $dry == "1" ]]; then
	    return
    fi

    "$@"
}

log "Matt-McConway Dev Env Installer"
log "https://github.com/Matt-McConway/dotfiles"
log "[RUN]: filter=$filter"

cd $script_dir
scripts=$(find installs -maxdepth 1 -mindepth 1 -perm -u+x -type f)

for script in $scripts; do
    if echo "$script" | grep -qv "$filter"; then
	    log "Filtering with [$filter]: $script"
	    continue
    fi
    
    log "Running script: $script"
    execute ./$script
done
